"""Core domain layer for pyVASP."""

from pyvasp.core.models import (
    BandGapChannel,
    BandGapSummary,
    ConvergenceProfile,
    ConvergenceProfilePoint,
    ConvergenceReport,
    DosMetadata,
    ElectronicStructureMetadata,
    EnergyPoint,
    GeneratedInputBundle,
    MagnetizationSummary,
    OutcarDiagnostics,
    OutcarIonicSeries,
    OutcarIonicSeriesPoint,
    OutcarObservables,
    OutcarSummary,
    RelaxInputSpec,
    RelaxStructure,
    StressTensor,
    StructureAtom,
)
from pyvasp.core.payloads import (
    BatchSummaryRequestPayload,
    BatchSummaryResponsePayload,
    ConvergenceProfileRequestPayload,
    ConvergenceProfileResponsePayload,
    DiagnosticsRequestPayload,
    DiagnosticsResponsePayload,
    ElectronicMetadataRequestPayload,
    ElectronicMetadataResponsePayload,
    ExportTabularRequestPayload,
    ExportTabularResponsePayload,
    GenerateRelaxInputRequestPayload,
    GenerateRelaxInputResponsePayload,
    IonicSeriesRequestPayload,
    IonicSeriesResponsePayload,
    SummaryRequestPayload,
    SummaryResponsePayload,
)
from pyvasp.core.errors import AppError, ErrorCode, ParseError, PyVaspError, ValidationError
from pyvasp.core.result import AppResult

__all__ = [
    "AppResult",
    "AppError",
    "BandGapChannel",
    "BandGapSummary",
    "BatchSummaryRequestPayload",
    "BatchSummaryResponsePayload",
    "ConvergenceProfile",
    "ConvergenceProfilePoint",
    "ConvergenceProfileRequestPayload",
    "ConvergenceProfileResponsePayload",
    "ConvergenceReport",
    "DiagnosticsRequestPayload",
    "DiagnosticsResponsePayload",
    "DosMetadata",
    "ElectronicMetadataRequestPayload",
    "ElectronicMetadataResponsePayload",
    "ElectronicStructureMetadata",
    "ErrorCode",
    "EnergyPoint",
    "ExportTabularRequestPayload",
    "ExportTabularResponsePayload",
    "GeneratedInputBundle",
    "GenerateRelaxInputRequestPayload",
    "GenerateRelaxInputResponsePayload",
    "IonicSeriesRequestPayload",
    "IonicSeriesResponsePayload",
    "MagnetizationSummary",
    "OutcarDiagnostics",
    "OutcarIonicSeries",
    "OutcarIonicSeriesPoint",
    "OutcarObservables",
    "OutcarSummary",
    "RelaxInputSpec",
    "RelaxStructure",
    "StressTensor",
    "StructureAtom",
    "SummaryRequestPayload",
    "SummaryResponsePayload",
    "ParseError",
    "PyVaspError",
    "ValidationError",
]
