"""Core domain layer for pyVASP."""

from pyvasp.core.models import (
    BandGapChannel,
    BandGapSummary,
    ConvergenceProfile,
    ConvergenceProfilePoint,
    ConvergenceReport,
    DosMetadata,
    ElectronicStructureMetadata,
    EnergyPoint,
    GeneratedInputBundle,
    MagnetizationSummary,
    OutcarDiagnostics,
    OutcarObservables,
    OutcarSummary,
    RelaxInputSpec,
    RelaxStructure,
    StressTensor,
    StructureAtom,
)
from pyvasp.core.payloads import (
    ConvergenceProfileRequestPayload,
    ConvergenceProfileResponsePayload,
    DiagnosticsRequestPayload,
    DiagnosticsResponsePayload,
    ElectronicMetadataRequestPayload,
    ElectronicMetadataResponsePayload,
    GenerateRelaxInputRequestPayload,
    GenerateRelaxInputResponsePayload,
    SummaryRequestPayload,
    SummaryResponsePayload,
)
from pyvasp.core.errors import AppError, ErrorCode, ParseError, PyVaspError, ValidationError
from pyvasp.core.result import AppResult

__all__ = [
    "AppResult",
    "AppError",
    "BandGapChannel",
    "BandGapSummary",
    "ConvergenceProfile",
    "ConvergenceProfilePoint",
    "ConvergenceProfileRequestPayload",
    "ConvergenceProfileResponsePayload",
    "ConvergenceReport",
    "DiagnosticsRequestPayload",
    "DiagnosticsResponsePayload",
    "DosMetadata",
    "ElectronicMetadataRequestPayload",
    "ElectronicMetadataResponsePayload",
    "ElectronicStructureMetadata",
    "ErrorCode",
    "EnergyPoint",
    "GeneratedInputBundle",
    "GenerateRelaxInputRequestPayload",
    "GenerateRelaxInputResponsePayload",
    "MagnetizationSummary",
    "OutcarDiagnostics",
    "OutcarObservables",
    "OutcarSummary",
    "RelaxInputSpec",
    "RelaxStructure",
    "StressTensor",
    "StructureAtom",
    "SummaryRequestPayload",
    "SummaryResponsePayload",
    "ParseError",
    "PyVaspError",
    "ValidationError",
]
